[workspace]

members = [ "examples/cool_scenes",
    "examples/dodger",
    "examples/empty", "examples/flappy_bird",
    "examples/pong",
    "jot", "jot_asset",
    "jot_collections",
    "jot_ecs",
    "jot_fixed",
    "jot_game",
    "jot_gpu",
    "jot_input",
    "jot_math",
    "jot_renderer2d", "jot_scene",
    "jot_scheme",
    "jot_window",
]
