[package]
edition = "2024"
name    = "jot_gpu"
version = "0.1.0"

[dependencies]
jot_gpu_proc_macros = { path = "proc_macros" }
jot_math            = { path = "../jot_math" }
jot_window          = { path = "../jot_window" }

bevy_ecs = "0.15.3"
crevice  = "0.18.0"
pollster = "0.4.0"
wgpu     = "25.0.1"
winit    = "0.30.9"
