[package]
edition = "2024"
name    = "jot_scheme"
version = "0.1.0"

[dependencies]
jot_scheme_proc_macros = { path = "proc_macros" }

jot_collections = { path = "../jot_collections" }
jot_input       = { path = "../jot_input" }
jot_macros      = { path = "../jot_macros" }
jot_math        = { path = "../jot_math" }
