[package]
edition = "2024"
name    = "jot_renderer2d"
version = "0.1.0"

[dependencies]
jot_camera = { path = "../jot_camera" }
jot_gpu    = { path = "../jot_gpu" }
jot_math   = { path = "../jot_math" }

const_format = { version = "0.2.34", features = [ "fmt" ] }
crevice      = "0.18.0"
wgpu         = "25.0.1"
wgsl-inline  = "0.2.1"
