[package]
edition = "2024"
name    = "jot_math"
version = "0.1.0"

[dependencies]
crevice = "0.18.0"
ggmath = { version = "0.12.1", features = [
    "crevice",
    "forward",
    "full",
    "right",
    "serde",
    "up",
] }
jot_macros = { path = "../jot_macros" }
jot_serialize = { path = "../jot_serialize" }
