[package]
edition = "2024"
name    = "jot"
version = "0.1.0"

[dependencies]
jot_asset       = { path = "../jot_asset", optional = true }
jot_collections = { path = "../jot_collections", optional = true }
jot_ecs         = { path = "../jot_ecs", optional = true }
jot_fixed       = { path = "../jot_fixed", optional = true }
jot_game        = { path = "../jot_game", optional = true }
jot_gpu         = { path = "../jot_gpu", optional = true }
jot_input       = { path = "../jot_input", optional = true }
jot_math        = { path = "../jot_math", optional = true }
jot_renderer2d  = { path = "../jot_renderer2d", optional = true }
jot_scheme      = { path = "../jot_scheme", optional = true }
jot_window      = { path = "../jot_window", optional = true }
paste           = "1.0.15"

[features]
asset       = [ "jot_asset" ]
collections = [ "jot_collections" ]
ecs         = [ "jot_ecs" ]
fixed       = [ "jot_fixed" ]
game        = [ "gpu", "input", "jot_game", "math" ]
gpu         = [ "jot_gpu", "math" ]
input       = [ "jot_input", "math" ]
math        = [ "jot_math" ]
renderer2d  = [ "gpu", "jot_renderer2d" ]
scheme      = [ "collections", "input", "jot_scheme", "math" ]
window      = [ "input", "jot_window" ]
