[package]
edition = "2024"
name    = "jot_gpu_proc_macros"
version = "0.1.0"

[lib]

proc-macro = true

[dependencies]
derive-syn-parse = "0.2.0"
naga             = { version = "25.0.1", features = [ "wgsl-in", "wgsl-out" ] }
proc-macro2      = "1.0.95"
quote            = "1.0.40"
syn              = "2.0.104"
uuid             = "1.12.0"
